name: Auto update clash
on:
    workflow_dispatch:
    schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "10 */1 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #  with:
    #    persist-credentials: false
    #    fetch-depth: 0
    - name: Create local changes
      run: |
        rm clash
        #wget -O clash 'https://convert.v2ray-subscribe.workers.dev/?url=https://raw.githubusercontent.com/sattheptonghop/4g/main/v2ray&q=dl.kgvn.garenanow.com&flag=clash'
    - name: Create v2ray2
      run: |
        set -x
        # Đường dẫn đến file.txt
        file="v2ray1"

        # Tên file để lưu kết quả
        output_file="v2ray"
        rm -f "$output_file"
        
        # Kiểm tra xem tệp tồn tại
        if [ -f "$file" ]; then
            # Mở tệp và đọc từng dòng
            while IFS= read -r line; do
                # Kiểm tra nếu $line chứa chuỗi "http"
                if [[ $line == "http"* ]]; then
                    url="https://convert.v2ray-subscribe.workers.dev/?url=$line"
                    result=$(curl -s "$url")   # Truy cập và lấy nội dung từ trang web

                    # Kiểm tra nếu $result không rỗng
                    if [ -n "$result" ]; then
                        # Kiểm tra nếu $result không chứa chuỗi "html"
                        if [[ ! $result == *"html"* ]]; then
                            echo "$result" >> "$output_file"
                        fi
                    fi
                fi
            done < "$file"
            wget -O clash "https://convert.v2ray-subscribe.workers.dev/?url=$(cat $output_file)&flag=clash"
        else
            echo "Tệp $file không tồn tại."
        fi
    - name: Edit clash
      run: |
        #sed -i 's/select,/select,/p' clash
        sed -i 's/select,/url-test,/g' clash
        #sed -i 's/select,/fallback,/g' clash
        sed -i 's/cipher: http/cipher: auto/g' clash
            #sed -i 's/\] \}/\], url: "http:\/\/www.gstatic.com\/generate_204", interval: 60 \}/2g' clash
        sed -i 's/"] }/"], url: "http:\/\/www.gstatic.com\/generate_204", interval: 30 }/g' clash
        sed -i "s/T.ME\/SHARE_V2RAY_FILE/$(date +'%Y-%m-%d-%H-%M-%S')/1g" clash
            #sed -i '/ (1)/d' clash
            #sed -i '/ (2)/d' clash
    - name: Commit files
      run: |
        git config --local user.email "tuananh88c25@gmail.com"
        git config --local user.name "sattheptonghop"
        git add clash #--all
        git add v2ray
        git commit --allow-empty -m "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
